package VistaControlador;

import Modelo.Base_de_Datos;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.UIManager;

public class Ventana_Principal extends javax.swing.JFrame {

    public static String mostrarPanelContrasena() {
        // Crear un JDialog en lugar de JFrame para una mejor experiencia de usuario
        JDialog dialog = new JDialog();
        dialog.setTitle("Ingreso de Contraseña");
        dialog.setModal(true); // Hacer el diálogo modal para que bloquea la interacción con otras ventanas
        dialog.setSize(300, 150);
        dialog.setLocationRelativeTo(null); // Centrar el diálogo

        // Crear un JPanel
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(3, 1)); // Usar un GridLayout para organizar los componentes

        // Crear el campo de contraseña
        JPasswordField passwordField = new JPasswordField();
        panel.add(new JLabel("Ingrese su contraseña:")); // Etiqueta para el campo
        panel.add(passwordField); // Agregar el campo de contraseña al JPanel

        // Crear el botón de confirmar
        JButton confirmarButton = new JButton("Confirmar");
        panel.add(confirmarButton); // Agregar el botón al JPanel

        // Añadir acción al botón
        confirmarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener la contraseña ingresada
                String contrasena = new String(passwordField.getPassword());
                if (!contrasena.isEmpty()) {
                    dialog.dispose(); // Cerrar el diálogo
                    // Retornar la contraseña
                    JOptionPane.showMessageDialog(dialog, "Contraseña ingresada: " + contrasena);
                } else {
                    JOptionPane.showMessageDialog(dialog, "Por favor, ingrese una contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        // Agregar el panel al diálogo
        dialog.add(panel);
        dialog.setVisible(true); // Hacer visible el diálogo

        // Retornar la contraseña ingresada por el usuario
        return new String(passwordField.getPassword());
    }

    public JButton getBotonCerrarSesion() {
        return botonCerrarSesion;
    }

    public void setBotonCerrarSesion(JButton botonCerrarSesion) {
        this.botonCerrarSesion = botonCerrarSesion;
    }

    public JLabel getTextoBienvenido() {
        return textoBienvenido;
    }

    public void setTextoBienvenido(JLabel textoBienvenido) {
        this.textoBienvenido = textoBienvenido;
    }

    public JLabel getTextoUsuarioLogeado() {
        return textoUsuarioLogeado;
    }

    public void setTextoUsuarioLogeado(JLabel textoUsuarioLogeado) {
        this.textoUsuarioLogeado = textoUsuarioLogeado;
    }

    public void cerrarVentanaAbrirRegistrar() {
        Ventana_RegistrarUsuarios ventana_aux = new Ventana_RegistrarUsuarios();  // Crear la nueva ventana
        ventana_aux.setVisible(true);
        this.dispose();
    }

    public void cerrarVentanaAbrirLogin() {
        Ventana_Login ventana_aux = new Ventana_Login();  // Crear la nueva ventana
        ventana_aux.setVisible(true);
        this.dispose();
    }

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textoUsuarioLogeado = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JButton();
        botonNuevoUsuario = new javax.swing.JButton();
        botonCambiarContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);

        textoBienvenido.setText("BIENVENID@");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Imagen_User.png"))); // NOI18N

        textoUsuarioLogeado.setText("El usuario");

        botonCerrarSesion.setText("Cerrar Sesion");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        botonNuevoUsuario.setText("Nuevo Usuario");
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        botonCambiarContraseña.setText("Cambiar Contraseña");
        botonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoBienvenido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(textoUsuarioLogeado)
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCambiarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(textoBienvenido)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(textoUsuarioLogeado)
                .addGap(32, 32, 32)
                .addComponent(botonNuevoUsuario)
                .addGap(18, 18, 18)
                .addComponent(botonCambiarContraseña)
                .addGap(18, 18, 18)
                .addComponent(botonCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        cerrarVentanaAbrirLogin();
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioActionPerformed
        cerrarVentanaAbrirRegistrar();
    }//GEN-LAST:event_botonNuevoUsuarioActionPerformed

    private void botonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarContraseñaActionPerformed
        Ventana_Login ventana_aux = new Ventana_Login();
        
        if(ventana_aux.getTextoUsuario().getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error, no se ingreso con ningun usuario.");
            return;
        }
        
        String passwd = mostrarPanelContrasena();
        Base_de_Datos.actualizarContrasena(ventana_aux.getTextoUsuario().getText(), passwd);

        if (passwd != null) {
            JOptionPane.showMessageDialog(null, "Contraseña ingresada: " + passwd);
            // Aquí puedes usar la contraseña como necesites
        } else {
            JOptionPane.showMessageDialog(null, "No se ingresó ninguna contraseña.");
        }

    }//GEN-LAST:event_botonCambiarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace(); // Manejo de excepciones
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCambiarContraseña;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoBienvenido;
    private javax.swing.JLabel textoUsuarioLogeado;
    // End of variables declaration//GEN-END:variables
}
